-- Live execution telemetry for the fixed Messenger workflow dashboard.
create table if not exists public.workflow_executions (
  id text primary key,
  customer_id text not null,
  message text,
  ad_id text,
  product_id bigint references public.products(id) on delete set null,
  product_name text,
  current_node text,
  active_edge text,
  visited_nodes text[] not null default '{}',
  status text not null default 'running' check (status in ('running', 'completed', 'error')),
  error text,
  started_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.workflow_events (
  id bigint generated by default as identity primary key,
  execution_id text not null references public.workflow_executions(id) on delete cascade,
  event_type text not null check (event_type in (
    'workflow_started', 'node_started', 'node_completed',
    'edge_transfer', 'node_error', 'workflow_completed'
  )),
  node text,
  source_node text,
  target_node text,
  status text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists workflow_executions_updated_at_idx
  on public.workflow_executions (updated_at desc);
create index if not exists workflow_events_execution_created_idx
  on public.workflow_events (execution_id, created_at desc);

alter table public.workflow_executions enable row level security;
alter table public.workflow_events enable row level security;

drop policy if exists "workflow dashboard read executions" on public.workflow_executions;
create policy "workflow dashboard read executions"
  on public.workflow_executions for select
  to anon, authenticated
  using (true);

drop policy if exists "workflow dashboard read events" on public.workflow_events;
create policy "workflow dashboard read events"
  on public.workflow_events for select
  to anon, authenticated
  using (true);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'workflow_executions'
  ) then
    alter publication supabase_realtime add table public.workflow_executions;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'workflow_events'
  ) then
    alter publication supabase_realtime add table public.workflow_events;
  end if;
end $$;

-- Keep the dashboard fast; adjust the retention window if longer history is needed.
-- delete from public.workflow_events where created_at < now() - interval '7 days';
-- delete from public.workflow_executions where started_at < now() - interval '7 days';
